=== CastSpellar/tsiw-project/trunk/rent-a-house/houses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- INCLUDES -->
    <xs:include schemaLocation="rooms.xsd"/>
    
    <!-- CASAS -->
    <xs:element name="houses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="house">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="reference" type="xs:int"/>
                            <xs:element name="location" type="typeLocation"/>
                            <xs:element name="situation" type="xs:string"/>
                            <xs:element name="condition" type="typeCondition"/>
                            <xs:element name="type" type="typeRent"/>
                            <xs:element name="area" type="xs:int"/>
                            <!--  -->
                            <xs:element name="rooms" type="typeRoom"/>
                            <xs:element name="facilities"/>
                            
                            <xs:element name="personsAllowed" type="xs:int"/>
                            <xs:element name="roomMateAllowed" type="xs:boolean"/>
                            <xs:element name="petsAllowed" type="xs:boolean"/>
                            <xs:element name="childrenAllowed" type="xs:boolean"/>
                            <xs:element name="smokingAllowed" type="xs:boolean"/>
                            <xs:element name="livingRoom" type="xs:boolean"/>
                            
                            <!--  -->
                            <xs:element name="comunityOptions"/>
                            <xs:element name="transportOptions" type="typeTransport"/>
                            <xs:element name="furniture" type="xs:boolean"/>
                            
                            
                            <xs:element name="deposit" type="xs:int"/>
                            <xs:element name="price" type="xs:int"/>
                            <xs:element name="availability" type="typeDuration"/>
                            <xs:element name="duration" type="xs:int"/>
                            <xs:element name="others"/>
                            <xs:element name="comments"/>
                            <xs:element name="picture"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="typeDuration">
        <xs:sequence minOccurs="1">
            <xs:element name="from" type="xs:date"/>
            <xs:element name="to" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="typeLocation">
        <xs:sequence minOccurs="1">
            <xs:element name="country" type="xs:date"/>
            <xs:element name="region" type="xs:date"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="district" type="xs:string"/>
            <xs:element name="comments" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="typeRent">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Room"/>
            <xs:enumeration value="Flat"/>
            <xs:enumeration value="House"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="typeCondition">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Very Poor"/>
            <xs:enumeration value="Poor"/>
            <xs:enumeration value="Reasonable"/>
            <xs:enumeration value="Good"/>
            <xs:enumeration value="Very Good"/>
            <xs:enumeration value="Excelent"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="typeTransport">
        <xs:sequence>
            <xs:element name="BUS" type="xs:boolean"/>
            <xs:element name="subway_Metro" type="xs:boolean"/>
            <xs:element name="train" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== CastSpellar/tsiw-project/trunk/rent-a-house/testHouses.xml
<?xml version="1.0" encoding="UTF-8"?>
<houses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/workspace/rent-a-house/houses.xsd">
    <house>
        <reference>01</reference>
        <location>
            <country>Portugal</country>
            <region>Lisboa</region>
            <city>Lisboa</city>
            <district>Benfica</district>
            <comments>Perto do Estádio da Luz</comments>
        </location>
        <situation>Center</situation>
        <condition>Good</condition>
        <type></type>
        <facilities>
            <Internet>true</Internet>
            <centralHeating>true</centralHeating>
            <cableTv>true</cableTv>
            <videoDVD>true</videoDVD>
            <refrigerator>true</refrigerator>
        </facilities>
        <personsAllowed>1</personsAllowed>
        <roomMateAllowed>false</roomMateAllowed>
        <petsAllowed>false</petsAllowed>
        <childrenAllowed>false</childrenAllowed>
        <smokingAllowed>false</smokingAllowed>
        <livingRoom>true</livingRoom>
        <comunityOptions>
            <Supermarket>true</Supermarket>
           <CoffeShop>true</CoffeShop>
        </comunityOptions>
        <transportOptions>
            <BUS>true</BUS>
            <subway_Metro>false</subway_Metro>
            <train>true</train>
        </transportOptions>
        <furniture>true</furniture>
        <deposit>100</deposit>
        <price>200</price>
        <availability>
            <from>2007-01-01</from>
            <to>2007-12-01</to>
        </availability>
        <duration>6</duration>
        <others></others>
        <comments>A casa é muita gira.</comments>
        <picture></picture>
    </house>
</houses>
